name: Bug Report
description: Report a problem you're experiencing
labels: bug, unconfirmed, low priority
body:
    - type: markdown
      attributes:
          value: |
              Before opening a bug report, please search the existing issues (both open and closed).

              ---
              
              Thank you for taking the time to report a bug! The more details you provide, the easier it will be to help you.
              Please ensure that you don't share any sensitive information like passwords or API keys.
    - type: input
      id: package-version
      attributes:
          label: Package Version
          description: Please provide the full version of the package you have installed.
          placeholder: 1.0.0
      validations:
          required: true
    - type: input
      id: php-version
      attributes:
          label: PHP Version
          description: Please provide the full PHP version of your server.
          placeholder: 8.2.0
      validations:
          required: true
    - type: input
      id: laravel-version
      attributes:
          label: Laravel Version
          description: Please provide the full Laravel version of your project.
          placeholder: 10.0.0
      validations:
          required: true
    - type: dropdown
      id: operating-system
      attributes:
          label: Which operating system do you use?
          description: Please select your primary operating system.
          options:
            - macOS
            - Windows
            - Linux
      validations:
          required: false
    - type: dropdown
      id: translation-service
      attributes:
          label: Translation Service
          description: Which translation service are you using?
          options:
            - AWS Translate
            - Google Cloud Translation
            - Azure AI Translator
            - DeepL
            - Other
      validations:
          required: true
    - type: textarea
      id: environment-details
      attributes:
          label: Environment Details
          description: Are there any other specifics about your environment that might be relevant?
          placeholder: Using Homestead, Nginx, etc.
      validations:
          required: false
    - type: textarea
      id: description
      attributes:
          label: Problem Description
          description: Provide a detailed account of the issue you encountered. What did you observe?
      validations:
          required: true
    - type: textarea
      id: expectation
      attributes:
          label: Expected Behavior
          description: Describe the outcome you anticipated to occur instead.
      validations:
          required: true
    - type: textarea
      id: steps
      attributes:
          label: Steps To Reproduce
          description: Outline the series of actions taken that led to the observed behavior.
      validations:
          required: true
    - type: textarea
      id: notes
      attributes:
          label: Notes
          description: Use this field to provide any other notes that you feel might be relevant to the issue.
      validations:
          required: false
