blank_issues_enabled: false
contact_links:
  - name: Have a Question?
    url: https://github.com/andrewdwallo/transmatic/discussions/new?category=q-a
    about: Seek assistance or clarification from the community.
  - name: Suggest a Feature
    url: https://github.com/andrewdwallo/transmatic/discussions/new?category=feature-requests
    about: Propose enhancements or new ideas for Transmatic.
  - name: Show & Tell Showcase
    url: https://github.com/andrewdwallo/transmatic/discussions/new?category=show-tell
    about: Share your work, inspire the community, and get feedback from fellow developers.
